---

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# required
version: 2

build:
  os: ubuntu-24.04
  commands:
      - curl -fsSL https://pixi.sh/install.sh | bash
      - /home/docs/.pixi/bin/pixi install
      - /home/docs/.pixi/bin/pixi run setup_stubs
      - /home/docs/.pixi/bin/pixi run doxygen
      - /home/docs/.pixi/bin/pixi run sphinx

sphinx:
  configuration: builds/stubs/conf.py  # Pointing to the generated conf.py
