# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    meson: "1.7.0"
    ninja: "1.12.1"
    doxygen: "1.13.2"

python:
  install:
    - method: pip
      path: docs/requirements.txt

sphinx:
  configuration: builds/stubs/conf.py  # Pointing to the generated conf.py

commands:
  - meson setup builds/stubs -Dpal=stubs
  - meson compile -C builds/stubs doxygen
  - meson compile -C builds/stubs sphinx

output:
  html: builds/stubs/docs/sphinx  # Directory where the HTML files are generated
