---

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

  jobs:
    install
      - curl -fsSL https://pixi.sh/install.sh | bash
      - pixi install
      - pixi shell
    build:
      html:
        - meson setup builds/stubs -Dpal=stubs
        - meson compile -C builds/stubs doxygen
        - meson compile -C builds/stubs sphinx

sphinx:
  configuration: builds/stubs/conf.py  # Pointing to the generated conf.py
