[project]
name = "tikli"
version = "0.1.0"
description = "Add a short description here"
authors = ["Adel Mamin <adel.mamin@exafore.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
meson = ">=1.4.0,<1.5"
ninja = ">=1.11.1,<1.12"
gcc = ">=13.2.0,<13.3"
ragel = ">=6.10,<7"
cppcheck = ">=2.13.4,<2.14"
clang = ">=18.1.7,<18.2"
zig = ">=0.9.1,<0.10"
make = ">=4.4.1,<5"
include-what-you-use = ">=0.22,<0.23"

[pypi-dependencies]
setuptools-scm = ">=8.1.0, <9"
