[workspace]
authors = ["Adel Mamin <adel@mm.st>"]
channels = ["conda-forge"]
description = "A Minimalist Asynchronous Toolkit"
name = "amast"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup_stubs = "CC=gcc CXX=g++ meson setup builds/stubs -Dunit_test=true -Dpal=stubs -Dbuildtype=debug -Db_lto=false"
setup_posix = "meson setup builds/posix -Dpal=posix"
setup_posix_debug = "meson setup builds/posix_debug -Dpal=posix -Dbuildtype=debug -Db_lto=false -Db_sanitize=none"
setup_posix_size = "meson setup builds/posix_size -Dpal=posix -Dbuildtype=minsize -Db_lto=false -Db_sanitize=none"
setup_libuv = "meson setup builds/libuv -Dpal=libuv"

style = "meson compile -C builds/stubs style"
cspell = "meson compile -C builds/stubs cspell"
cppcheck = "meson compile -C builds/stubs cppcheck"
tidy = "meson compile -C builds/stubs tidy"
iwyu = "meson compile -C builds/stubs iwyu"
doxygen = "meson compile -C builds/stubs doxygen"
sphinx = "meson compile -C builds/stubs sphinx"

test_stubs = "meson test -C builds/stubs"
test_posix = "meson test -C builds/posix"
test_posix_debug = "meson test -C builds/posix_debug"
test_libuv = "meson test -C builds/libuv"

libs_stubs = "meson compile -C builds/stubs"
libs_posix = "meson compile -C builds/posix"
libs_posix_debug = "meson compile -C builds/posix_debug"
libs_posix_size = "meson compile -C builds/posix_size"
libs_libuv = "meson compile -C builds/libuv"

stubs = { depends-on = ["setup_stubs", "libs_stubs", "test_stubs", "cppcheck", "iwyu", "style", "cspell", "tidy"] }
posix = { depends-on = ["setup_posix", "libs_posix", "test_posix"] }
posix_debug = { depends-on = ["setup_posix_debug", "libs_posix_debug", "test_posix_debug"] }
posix_size = { depends-on = ["setup_posix_size", "libs_posix_size"] }
libuv = { depends-on = ["setup_libuv", "libs_libuv", "test_libuv"] }

docs = { depends-on = ["setup_stubs", "doxygen", "sphinx"] }

all = { depends-on = ["stubs", "posix", "libuv", "docs"] }

[dependencies]
meson = ">=1.10.2,<2"
ninja = ">=1.13.2,<2"
gcc = ">=15.2.0,<15.3"
cppcheck = ">=2.20.0,<3"
clang = ">=22.1.0,<23"
make = ">=4.4.1,<5"
include-what-you-use = ">=0.26,<0.27"
cspell = ">=9.7.0,<10"
clang-tools = ">=22.1.0,<23"
binutils = ">=2.45.1,<3"
gdb = ">=17.1,<18"
ccache = ">=4.13.2,<5"
doxygen = ">=1.13.2,<2"
sphinx = ">=9.1.0,<10"
yamllint = ">=1.38.0,<2"
plantuml = ">=1.2026.2,<2"

[pypi-dependencies]
breathe = ">=4.36.0,<5"
setuptools-scm = ">=10.0.3,<11"
pallets-sphinx-themes = ">=2.5.0,<3"
sphinxcontrib-plantuml = ">=0.31,<0.32"