[project]
authors = ["Adel Mamin <adel@mm.st>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "amast"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup_posix = "meson setup builds/posix -Dunit_test=true -Dpal=posix"
setup_libuv = "meson setup builds/libuv -Dunit_test=true -Dpal=libuv"

style_posix = "meson compile -C builds/posix style"
cspell = "meson compile -C builds/posix cspell"
cppcheck_posix = "meson compile -C builds/posix cppcheck"
tidy_posix = "meson compile -C builds/posix tidy"

test_posix = "meson test -C builds/posix"
test_libuv = "meson test -C builds/libuv"

libs_posix = "meson compile -C builds/posix"
libs_libuv = "meson compile -C builds/libuv"

iwyu_posix = "meson compile -C builds/posix iwyu"
doxygen = "meson compile -C builds/posix doxygen"
sphinx = "meson compile -C builds/posix sphinx"

posix = { depends-on = ["setup_posix", "cspell", "doxygen", "sphinx", "iwyu_posix", "style_posix", "libs_posix", "cppcheck_posix", "test_posix"] }
libuv = { depends-on = ["setup_libuv", "libs_libuv", "test_libuv"] }
all = { depends-on = ["posix", "libuv"] }

[dependencies]
meson = ">=1.7.0,<2"
ninja = ">=1.12.1,<2"
gcc = ">=14.2.0,<14.3"
cppcheck = ">=2.16.0,<3"
clang = ">=19.1.7,<20"
make = ">=4.4.1,<5"
include-what-you-use = ">=0.23,<0.24"
cspell = ">=8.17.4,<9"
clang-tools = ">=19.1.7,<20"
binutils = ">=2.43,<3"
gdb = ">=15.1,<16"
ccache = ">=4.10.1,<5"
doxygen = ">=1.13.2,<2"
sphinx = ">=8.2.0,<9"
breathe = ">=4.35.0,<5"

[pypi-dependencies]
setuptools-scm = ">=8.1.0, <9"
pallets-sphinx-themes = ">=2.3.0, <3"
