[project]
authors = ["Adel Mamin <adel@mm.st>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "amast"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup_posix = "meson setup builds/posix -Dunit_test=true -Dpal=posix -Dao_type=preemptive"
style_posix = "meson compile -C builds/posix style"
cppcheck_posix = "meson compile -C builds/posix cppcheck"
tidy_posix = "meson compile -C builds/posix tidy"
test_posix = "meson test -C builds/posix"
libs_posix = "meson compile -C builds/posix"
iwyu_posix = "meson compile -C builds/posix iwyu"
posix = { depends-on = ["setup_posix", "libs_posix", "style_posix", "cppcheck_posix", "tidy_posix", "iwyu_posix", "test_posix"] }
setup_posix_cooperative = "meson setup builds/cooperative -Dunit_test=true -Dpal=posix -Dao_type=cooperative"
posix_cooperative = { depends-on = ["setup_posix_cooperative", "libs_posix", "style_posix", "cppcheck_posix", "tidy_posix", "iwyu_posix", "test_posix"] }
all = { depends-on = ["posix", "posix_cooperative"] }

[dependencies]
meson = ">=1.6.0,<2"
ninja = ">=1.12.1,<2"
gcc = ">=14.2.0,<14.3"
cppcheck = ">=2.16.0,<2.17"
clang = ">=18.1.8,<=18.1.8"
make = ">=4.4.1,<4.5"
include-what-you-use = ">=0.22,<0.23"

[pypi-dependencies]
setuptools-scm = ">=8.1.0, <9"
