[project]
authors = ["Adel Mamin <adel@mm.st>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "amast"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup = "meson setup build -Dunit_test=true"
style = "meson compile -C build style"
cppcheck = "meson compile -C build cppcheck"
tidy = "meson compile -C build tidy"
test = "meson test -C build"
libs = "meson compile -C build"
all = { depends-on = ["setup", "style", "cppcheck", "tidy", "libs", "test"] }

[dependencies]
meson = ">=1.6.0,<2"
ninja = ">=1.12.1,<2"
gcc = ">=14.2.0,<14.3"
cppcheck = ">=2.16.0,<2.17"
clang = ">=19.1.3,<19.2"
make = ">=4.4.1,<4.5"
include-what-you-use = ">=0.22,<0.23"

[pypi-dependencies]
setuptools-scm = ">=8.1.0, <9"
