[project]
authors = ["Adel Mamin <adel@mm.st>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "amast"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup_stubs = "meson setup builds/stubs -Dunit_test=true -Dpal=stubs"
setup_posix = "meson setup builds/posix -Dpal=posix"
setup_libuv = "meson setup builds/libuv -Dpal=libuv"

style = "meson compile -C builds/stubs style"
cspell = "meson compile -C builds/stubs cspell"
cppcheck = "meson compile -C builds/stubs cppcheck"
tidy = "meson compile -C builds/stubs tidy"
iwyu = "meson compile -C builds/stubs iwyu"
doxygen = "meson compile -C builds/stubs doxygen"
sphinx = "meson compile -C builds/stubs sphinx"

test_stubs = "meson test -C builds/stubs"
test_posix = "meson test -C builds/posix"
test_libuv = "meson test -C builds/libuv"

libs_stubs = "meson compile -C builds/stubs"
libs_posix = "meson compile -C builds/posix"
libs_libuv = "meson compile -C builds/libuv"

stubs = { depends-on = ["setup_stubs", "libs_stubs", "cspell", "doxygen", "sphinx", "iwyu", "style", "cppcheck", "test_stubs"] }
posix = { depends-on = ["setup_posix", "libs_posix", "test_posix"] }
libuv = { depends-on = ["setup_libuv", "libs_libuv", "test_libuv"] }

all = { depends-on = ["stubs", "posix", "libuv"] }

[dependencies]
meson = ">=1.7.0,<2"
ninja = ">=1.12.1,<2"
gcc = ">=14.2.0,<14.3"
cppcheck = ">=2.16.0,<3"
clang = ">=19.1.7,<20"
make = ">=4.4.1,<5"
include-what-you-use = ">=0.23,<0.24"
cspell = ">=8.17.5,<9"
clang-tools = ">=19.1.7,<20"
binutils = ">=2.43,<3"
gdb = ">=15.1,<16"
ccache = ">=4.10.1,<5"
doxygen = ">=1.13.2,<2"
sphinx = ">=8.2.1,<9"
breathe = ">=4.36.0,<5"
yamllint = ">=1.35.1,<2"

[pypi-dependencies]
setuptools-scm = ">=8.2.0, <9"
pallets-sphinx-themes = ">=2.3.0, <3"
