[project]
authors = ["Adel Mamin <adel@mm.st>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "amast"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup_posix = "meson setup builds/posix -Dunit_test=true -Dpal=posix"
style_posix = "meson compile -C builds/posix style"
cspell = "meson compile -C builds/posix cspell"
cppcheck_posix = "meson compile -C builds/posix cppcheck"
tidy_posix = "meson compile -C builds/posix tidy"
test_posix = "meson test -C builds/posix"
libs_posix = "meson compile -C builds/posix"
iwyu_posix = "meson compile -C builds/posix iwyu"
posix = { depends-on = ["setup_posix", "libs_posix", "style_posix", "cspell", "cppcheck_posix", "iwyu_posix", "test_posix"] }
all = { depends-on = ["posix"] }

[dependencies]
meson = ">=1.6.1,<2"
ninja = ">=1.12.1,<2"
gcc = ">=14.2.0,<14.3"
cppcheck = ">=2.16.0,<3"
clang = ">=19.1.7,<20"
make = ">=4.4.1,<5"
include-what-you-use = ">=0.23,<0.24"
cspell = ">=8.17.2,<9"
clang-tools = ">=19.1.7,<20"
binutils = ">=2.43,<3"
gdb = ">=15.1,<16"

[pypi-dependencies]
setuptools-scm = ">=8.1.0, <9"
